name: Validate Workflows
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths:
      - .github/actionlint-matcher.json
      - .github/zizmor.yml
      - .github/workflows/**
      - .github/actions/**
  pull_request:
    paths:
      - .github/actionlint-matcher.json
      - .github/zizmor.yml
      - .github/workflows/**
      - .github/actions/**
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
      - name: Run actionlint
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          uvx --from=actionlint-py actionlint -color
  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
      - name: Run zizmor
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uvx zizmor --pedantic --format=github .
